/**
 * AI Style Service — Uses Gemini to analyze video content and auto-select
 * the best caption style (font, color, animation) based on the content.
 */

import { GoogleGenAI } from "@google/genai";
import { Caption, CaptionStyle, EntryAnimation, WordHighlightMode, ExitAnimation } from "../types";
import { GEMINI_MODEL } from "../constants";

const Type = {
  STRING: "STRING",
  NUMBER: "NUMBER",
  INTEGER: "INTEGER",
  BOOLEAN: "BOOLEAN",
  ARRAY: "ARRAY",
  OBJECT: "OBJECT"
} as const;

const getApiKey = (): string => {
  const envKey = import.meta.env.VITE_GEMINI_API_KEY || import.meta.env.VITE_API_KEY;
  const key = envKey || localStorage.getItem('createrin_api_key');
  if (!key) throw new Error("API Key not found.");
  return key;
};

// ─────────────────────────────────────────────────────────
// THEME PRESETS — Complete style bundles for quick apply
// ─────────────────────────────────────────────────────────

export interface ThemePreset {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  captionStyle: CaptionStyle;
  fontFamily: string;
  fontWeight: string | number;
  textColor: string;
  bgEnabled: boolean;
  bgColor: string;
  bgPadding: number;
  bgRadius: number;
  strokeWidth: number;
  strokeColor: string;
  uppercase: boolean;
  entryAnimation: EntryAnimation;
  exitAnimation: ExitAnimation;
  wordHighlight: WordHighlightMode;
  animationSpeed: 'FAST' | 'MEDIUM' | 'SLOW';
  gradientColors?: string[];
  emojiPrefix?: string;   // Emoji char(s) prepended to caption text (rendered as animated GIF)
  emojiSuffix?: string;   // Emoji char(s) appended to caption text (rendered as animated GIF)
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'podcast',
    name: 'Podcast',
    category: 'Professional',
    description: 'Clean, minimal, professional narration',
    icon: '🎙️',
    captionStyle: CaptionStyle.CINEMATIC,
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 12,
    bgRadius: 8,
    strokeWidth: 0,
    strokeColor: '#000000',
    uppercase: false,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'SPOTLIGHT',
    animationSpeed: 'SLOW',
  },
  {
    id: 'motivation',
    name: 'Motivation',
    category: 'Dynamic',
    description: 'Bold, impactful, high-energy text',
    icon: '🔥',
    captionStyle: CaptionStyle.HORMOZI,
    fontFamily: "'Bebas Neue', display",
    fontWeight: 900,
    textColor: '#FACC15',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 12,
    bgRadius: 8,
    strokeWidth: 8,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'KARAOKE',
    animationSpeed: 'FAST',
  },
  {
    id: 'hyper-impact-bold',
    name: 'Hyper-Impact Bold',
    category: 'Dynamic',
    description: 'Hormozi gradient — white words, orange→yellow keyword pop',
    icon: '💥',
    captionStyle: CaptionStyle.HYPER_IMPACT_BOLD,
    fontFamily: "'Anton', sans-serif",
    fontWeight: 'italic 900',
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 12,
    bgRadius: 8,
    strokeWidth: 16,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
    gradientColors: ['#F97316', '#FBBF24', '#FDE047'],
  },
  {
    id: 'meme',
    name: 'Meme',
    category: 'Fun',
    description: 'Loud, comic, attention-grabbing text',
    icon: '😂',
    captionStyle: CaptionStyle.BEAST_MODE,
    fontFamily: "'Bangers', cursive",
    fontWeight: 400,
    textColor: '#FFD700',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 12,
    bgRadius: 8,
    strokeWidth: 8,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'ZOOM_IN',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    category: 'Professional',
    description: 'Elegant, dark tones, slow transitions',
    icon: '🎬',
    captionStyle: CaptionStyle.LUXURY_GOLD,
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    textColor: '#FCD34D',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 12,
    bgRadius: 8,
    strokeWidth: 0,
    strokeColor: '#000000',
    uppercase: false,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'NONE',
    animationSpeed: 'SLOW',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    category: 'Dynamic',
    description: 'Neon glow, high-energy, streamer vibes',
    icon: '🎮',
    captionStyle: CaptionStyle.NEON_GLOW,
    fontFamily: "'Orbitron', sans-serif",
    fontWeight: 900,
    textColor: '#00FFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 12,
    bgRadius: 8,
    strokeWidth: 3,
    strokeColor: '#003344',
    uppercase: true,
    entryAnimation: 'GLITCH',
    exitAnimation: 'GLITCH_OUT',
    wordHighlight: 'BOX',
    animationSpeed: 'FAST',
  },
  {
    id: 'tiktok_viral',
    name: 'TikTok Viral',
    category: 'Trending',
    description: 'The classic trending word-pop style',
    icon: '📱',
    captionStyle: CaptionStyle.WORD_POP,
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0.5)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 6,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'SHATTER',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'KARAOKE',
    animationSpeed: 'FAST',
  },
  {
    id: 'fire_pop',
    name: 'Fire Pop',
    category: 'Dynamic',
    description: 'Flaming word highlight for hype moments',
    icon: '🌋',
    captionStyle: CaptionStyle.FIRE_WORD,
    fontFamily: "'Anton', sans-serif",
    fontWeight: 900,
    textColor: '#FF9500',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 4,
    strokeColor: '#8B1A00',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'FIRE',
    animationSpeed: 'FAST',
  },
  {
    id: 'rainbow_wave',
    name: 'Rainbow Wave',
    category: 'Fun',
    description: 'Colorful cycling text',
    icon: '🌈',
    captionStyle: CaptionStyle.RAINBOW_BURST,
    fontFamily: "'Fredoka', sans-serif",
    fontWeight: 700,
    textColor: '#FF6B6B',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 5,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'WIPE_RIGHT',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'RAINBOW',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'vlog_minimal',
    name: 'Vlog Minimal',
    category: 'Professional',
    description: 'Clean fade for lifestyle and vlogs',
    icon: '☕',
    captionStyle: CaptionStyle.CLEAN_WHITE,
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    textColor: '#FFFFFF',
    bgEnabled: true,
    // Richer semi-transparent background — visible on all backgrounds
    bgColor: 'rgba(8, 8, 18, 0.72)',
    bgPadding: 24,
    bgRadius: 18,
    strokeWidth: 0,
    strokeColor: '#000000',
    uppercase: false,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'SPOTLIGHT',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'neon_nights',
    name: 'Neon Nights',
    category: 'Dynamic',
    description: 'Cyberpunk karaoke glow',
    icon: '🔮',
    captionStyle: CaptionStyle.KARAOKE_FLOW,
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 900,
    textColor: '#00F5FF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: '#004F60',
    uppercase: false,
    entryAnimation: 'GLITCH',
    exitAnimation: 'GLITCH_OUT',
    wordHighlight: 'WAVE',
    animationSpeed: 'FAST',
  },
  {
    id: 'highlight_slam',
    name: 'Highlight Slam',
    category: 'Trending',
    description: 'Bold yellow highlight box per word',
    icon: '✍️',
    captionStyle: CaptionStyle.HIGHLIGHT_BOX,
    fontFamily: "'Inter', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: '#000',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'BOX',
    animationSpeed: 'FAST',
  },
  {
    id: 'gradient_dream',
    name: 'Gradient Dream',
    category: 'Fun',
    description: 'Vivid multi-color gradient text',
    icon: '🌊',
    captionStyle: CaptionStyle.GRADIENT_DREAM,
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: '#000',
    uppercase: true,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
    gradientColors: ['#6366F1', '#EC4899', '#F97316'],
  },
  {
    id: 'shatter_glass',
    name: 'Shatter Glass',
    category: 'Unique',
    description: 'Sci-fi ice-crystal text that cracks in like broken glass',
    icon: '🧊',
    captionStyle: CaptionStyle.GLITCH_RGB,
    fontFamily: "'Orbitron', sans-serif",
    fontWeight: 900,
    textColor: '#FF00FF',
    bgEnabled: true,
    bgColor: 'rgba(10, 0, 40, 0.75)',
    bgPadding: 18,
    bgRadius: 4,
    strokeWidth: 4,
    strokeColor: '#00FFFF',
    uppercase: true,
    entryAnimation: 'SHATTER',
    exitAnimation: 'GLITCH_OUT',
    wordHighlight: 'SPARKLE',
    animationSpeed: 'FAST',
    gradientColors: ['#00FFFF', '#FF00FF', '#FFE600'],
  },
  {
    id: 'emoji_fire',
    name: 'Emoji Fire',
    category: 'Fun',
    description: 'Blazing animated fire emojis bracketing bold text',
    icon: '🔥',
    captionStyle: CaptionStyle.EMOJI_FIRE,
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    textColor: '#FFF200',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 14,
    strokeColor: '#CC2200',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'FIRE',
    animationSpeed: 'FAST',
    gradientColors: ['#FF4500', '#FF8C00', '#FFD700'],
    emojiPrefix: '🔥',
    emojiSuffix: '🔥',
  },
  {
    id: 'emoji_sparkle',
    name: 'Emoji Sparkle',
    category: 'Fun',
    description: 'Magical sparkle emojis with purple glow effect',
    icon: '✨',
    captionStyle: CaptionStyle.EMOJI_SPARKLE,
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 6,
    strokeColor: '#4C1D95',
    uppercase: false,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'SPARKLE',
    animationSpeed: 'MEDIUM',
    gradientColors: ['#7C3AED', '#EC4899', '#A855F7'],
    emojiPrefix: '✨',
    emojiSuffix: '✨',
  },
  {
    id: 'emoji_party',
    name: 'Emoji Party',
    category: 'Fun',
    description: 'Festive party emojis with rainbow pop energy',
    icon: '🎉',
    captionStyle: CaptionStyle.EMOJI_PARTY,
    fontFamily: "'Bangers', cursive",
    fontWeight: 400,
    textColor: '#FFD700',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 12,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'ZOOM_IN',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'RAINBOW',
    animationSpeed: 'FAST',
    gradientColors: ['#FF6B6B', '#FECA57', '#48DBFB', '#FF9FF3'],
    emojiPrefix: '🎉',
    emojiSuffix: '🎊',
  },
  {
    id: 'emoji_heart',
    name: 'Emoji Heart',
    category: 'Fun',
    description: 'Romantic heart emojis with pink glow and love energy',
    icon: '❤️',
    captionStyle: CaptionStyle.EMOJI_HEART,
    fontFamily: "'Pacifico', cursive",
    fontWeight: 400,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 8,
    strokeColor: '#FF1493',
    uppercase: false,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'MEDIUM',
    gradientColors: ['#FF69B4', '#FF1493', '#FFB6C1'],
    emojiPrefix: '❤️',
    emojiSuffix: '💕',
  },
  {
    id: 'emoji_hype',
    name: 'Emoji Hype',
    category: 'Fun',
    description: 'High-energy hype emojis with explosive impact',
    icon: '🚀',
    captionStyle: CaptionStyle.EMOJI_HYPE,
    fontFamily: "'Impact', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 16,
    strokeColor: '#FF4500',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'FIRE',
    animationSpeed: 'FAST',
    gradientColors: ['#FF4500', '#FF6B35', '#FFD700'],
    emojiPrefix: '🔥',
    emojiSuffix: '🚀',
  },
  {
    id: 'emoji_auto',
    name: '🌟 Emoji Auto Matcher',
    category: 'Fun',
    description: 'AI automatically picks the perfect animated emoji for each sentence',
    icon: '✨',
    captionStyle: CaptionStyle.EMOJI_AUTO,
    fontFamily: "'Bebas Neue', display",
    fontWeight: 400,
    textColor: '#FFFFFF',
    bgEnabled: true,
    bgColor: 'rgba(0,0,0,0.45)',
    bgPadding: 20,
    bgRadius: 16,
    strokeWidth: 10,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
    gradientColors: [],
  },
  {
    id: 'animated_emojis',
    name: '🎬 Animated Emojis',
    category: 'Fun',
    description: 'Vibrant animated GIF emojis that bring captions to life with motion',
    icon: '❤️',
    captionStyle: CaptionStyle.EMOJI_HEART,
    fontFamily: "'Bebas Neue', display",
    fontWeight: 700,
    textColor: '#FFFFFF',
    bgEnabled: true,
    bgColor: 'rgba(0,0,0,0.6)',
    bgPadding: 18,
    bgRadius: 20,
    strokeWidth: 8,
    strokeColor: '#FF3366',
    uppercase: true,
    entryAnimation: 'BOUNCE',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
    gradientColors: ['#FF3366', '#FF6B35', '#FFD700'],
    emojiPrefix: '❤️',
    emojiSuffix: '✨',
  },
  {
    id: 'apple_minimal',
    name: 'Apple Minimal',
    category: 'Professional',
    description: 'Ultra-clean, high-contrast sans-serif typical of hardware keynotes',
    icon: '🍎',
    captionStyle: CaptionStyle.APPLE_MINIMAL,
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: '#000000',
    uppercase: false,
    entryAnimation: 'FADE_IN',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'SPOTLIGHT',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'bounce_stamp',
    name: 'Bounce Stamp',
    category: 'Trending',
    description: 'Words slam down like a rubber stamp',
    icon: '💥',
    captionStyle: CaptionStyle.BOUNCE_STAMP,
    fontFamily: "'Anton', sans-serif",
    fontWeight: 900,
    textColor: '#FF3366',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 4,
    strokeColor: '#FFFFFF',
    uppercase: true,
    entryAnimation: 'STAMP',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'slide_reveal',
    name: 'Slide Reveal',
    category: 'Professional',
    description: 'Clean wiping reveal effect',
    icon: '↔️',
    captionStyle: CaptionStyle.SLIDE_REVEAL,
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    textColor: '#00E5FF',
    bgEnabled: true,
    bgColor: 'rgba(0,0,0,0.6)',
    bgPadding: 10,
    bgRadius: 4,
    strokeWidth: 0,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'SLIDE_DOWN',
    exitAnimation: 'SLIDE_UP',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'blur_fade',
    name: 'Blur Fade',
    category: 'Professional',
    description: 'Cinematic unblur reveal',
    icon: '🌫️',
    captionStyle: CaptionStyle.BLUR_FADE,
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 600,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 2,
    strokeColor: '#000000',
    uppercase: false,
    entryAnimation: 'BLUR_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'pop_out',
    name: 'Pop Out',
    category: 'Fun',
    description: 'Splits open from the center',
    icon: '🍿',
    captionStyle: CaptionStyle.POP_OUT,
    fontFamily: "'Bebas Neue', display",
    fontWeight: 400,
    textColor: '#FF0055',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 3,
    strokeColor: '#FFFFFF',
    uppercase: true,
    entryAnimation: 'SPLIT_OPEN',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'spring_slam',
    name: 'Spring Slam',
    category: 'Trending',
    description: 'Intense springy appearance',
    icon: '🪀',
    captionStyle: CaptionStyle.SPRING_SLAM,
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    textColor: '#00FF00',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 4,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'SPRING',
    exitAnimation: 'FLIP',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'flip_word',
    name: 'Flip Word',
    category: 'Dynamic',
    description: '3D flipping per word',
    icon: '🔄',
    captionStyle: CaptionStyle.FLIP_WORD,
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    textColor: '#FFD700',
    bgEnabled: true,
    bgColor: 'rgba(0,0,0,0.8)',
    bgPadding: 16,
    bgRadius: 8,
    strokeWidth: 0,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'FLIP_Y',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'elastic_drop',
    name: 'Elastic Drop',
    category: 'Fun',
    description: 'Rubber-band bounce effect',
    icon: '📉',
    captionStyle: CaptionStyle.ELASTIC_DROP,
    fontFamily: "'Fredoka', sans-serif",
    fontWeight: 700,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 4,
    strokeColor: '#9C27B0',
    uppercase: false,
    entryAnimation: 'ELASTIC',
    exitAnimation: 'ZOOM_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'scatter_gather',
    name: 'Scatter Gather',
    category: 'Unique',
    description: 'Words fly in from random directions',
    icon: '🌪️',
    captionStyle: CaptionStyle.SCATTER_GATHER,
    fontFamily: "'Orbitron', sans-serif",
    fontWeight: 900,
    textColor: '#00FFFF',
    bgEnabled: false,
    bgColor: 'rgba(0,0,0,0)',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 2,
    strokeColor: '#FF00FF',
    uppercase: true,
    entryAnimation: 'SCATTER_IN',
    exitAnimation: 'GLITCH_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'tiktok_native',
    name: 'TikTok Native',
    category: 'Trending',
    description: 'The native standard for TikTok captions',
    icon: '📱',
    captionStyle: CaptionStyle.TIKTOK_NATIVE,
    fontFamily: '"Proxima Nova", sans-serif',
    fontWeight: 700,
    textColor: '#FFFFFF',
    bgEnabled: true,
    bgColor: 'rgba(0, 0, 0, 0.65)',
    bgPadding: 16,
    bgRadius: 8,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: false,
    entryAnimation: 'NONE',
    exitAnimation: 'NONE',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'instagram_native',
    name: 'Instagram Classic',
    category: 'Trending',
    description: 'The classic Instagram Reels style',
    icon: '📸',
    captionStyle: CaptionStyle.INSTAGRAM_NATIVE,
    fontFamily: 'sans-serif',
    fontWeight: 800,
    textColor: '#000000',
    bgEnabled: true,
    bgColor: '#FFFFFF',
    bgPadding: 14,
    bgRadius: 4,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: false,
    entryAnimation: 'POP',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'KARAOKE',
    animationSpeed: 'FAST',
  },
  {
    id: 'word_spring',
    name: 'Word Spring',
    category: 'Dynamic',
    description: 'Dynamic word spring with physics',
    icon: '🪀',
    captionStyle: CaptionStyle.WORD_SPRING,
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 10,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'SPRING',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
  },
  {
    id: 'pill_badge',
    name: 'Pill Badge',
    category: 'Unique',
    description: 'Dynamic word-by-word pill backgrounds',
    icon: '💊',
    captionStyle: CaptionStyle.PILL_BADGE,
    fontFamily: "'Inter', sans-serif",
    fontWeight: 800,
    textColor: '#111111',
    bgEnabled: true,
    bgColor: '#FFFFFF',
    bgPadding: 24,
    bgRadius: 30,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: true,
    entryAnimation: 'POP',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'BOX',
    animationSpeed: 'FAST',
  },
  {
    id: 'speech_bubble',
    name: 'Speech Bubble',
    category: 'Fun',
    description: 'Comic-style speech bubble with tail',
    icon: '💬',
    captionStyle: CaptionStyle.SPEECH_BUBBLE,
    fontFamily: "'Comic Sans MS', sans-serif",
    fontWeight: 700,
    textColor: '#000000',
    bgEnabled: true,
    bgColor: '#FFFFFF',
    bgPadding: 24,
    bgRadius: 20,
    strokeWidth: 4,
    strokeColor: '#000000',
    uppercase: false,
    entryAnimation: 'POP',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'blur_reveal',
    name: 'Blur Reveal',
    category: 'Professional',
    description: 'Cinematic unblur reveal',
    icon: '🌫️',
    captionStyle: CaptionStyle.BLUR_REVEAL,
    fontFamily: "'Cinzel', serif",
    fontWeight: 600,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: false,
    entryAnimation: 'BLUR_IN',
    exitAnimation: 'DISSOLVE',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'split_reveal',
    name: 'Split Reveal',
    category: 'Dynamic',
    description: 'Splits open from the center',
    icon: '↔️',
    captionStyle: CaptionStyle.SPLIT_REVEAL,
    fontFamily: "'Anton', sans-serif",
    fontWeight: 400,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 8,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'SPLIT_OPEN',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
  },
  {
    id: 'neon_sign_flicker',
    name: 'Neon Flicker',
    category: 'Unique',
    description: 'Flickering neon sign glow',
    icon: '⚡',
    captionStyle: CaptionStyle.NEON_SIGN_FLICKER,
    fontFamily: "'Orbitron', sans-serif",
    fontWeight: 900,
    textColor: 'rgba(255,100,200,0.3)',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 4,
    strokeColor: '#330033',
    uppercase: true,
    entryAnimation: 'NONE',
    exitAnimation: 'NONE',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
  },
  {
    id: 'ticker_scroll',
    name: 'News Ticker',
    category: 'Trending',
    description: 'News-style continuous scrolling text',
    icon: '📰',
    captionStyle: CaptionStyle.TICKER_SCROLL,
    fontFamily: "'Space Mono', monospace",
    fontWeight: 700,
    textColor: '#000000',
    bgEnabled: true,
    bgColor: '#FFFFFF',
    bgPadding: 16,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: true,
    entryAnimation: 'NONE',
    exitAnimation: 'NONE',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'magnetic_words',
    name: 'Magnetic Scatter',
    category: 'Dynamic',
    description: 'Words scatter and merge in',
    icon: '🧲',
    captionStyle: CaptionStyle.MAGNETIC_WORDS,
    fontFamily: "'Outfit', sans-serif",
    fontWeight: 800,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 8,
    strokeColor: '#000000',
    uppercase: true,
    entryAnimation: 'SCATTER_IN',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
  },
  {
    id: 'perspective_3d',
    name: '3D Perspective',
    category: 'Unique',
    description: '3D spatial perspective rotation',
    icon: '🧊',
    captionStyle: CaptionStyle.PERSPECTIVE_3D,
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 6,
    strokeColor: '#1A1A1A',
    uppercase: true,
    entryAnimation: 'FLIP_Y',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'MEDIUM',
  },
  {
    id: 'brush_stroke',
    name: 'Brush Stroke',
    category: 'Fun',
    description: 'Artistic brush stroke background',
    icon: '🖌️',
    captionStyle: CaptionStyle.BRUSH_STROKE,
    fontFamily: "'Caveat', cursive",
    fontWeight: 700,
    textColor: '#FFFFFF',
    bgEnabled: true,
    bgColor: 'rgba(255, 50, 50, 0.9)',
    bgPadding: 10,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: false,
    entryAnimation: 'POP',
    exitAnimation: 'FADE_OUT',
    wordHighlight: 'NONE',
    animationSpeed: 'FAST',
  },
  {
    id: 'matrix_rain',
    name: 'Matrix Rain',
    category: 'Unique',
    description: 'Digital falling character effect',
    icon: '💻',
    captionStyle: CaptionStyle.MATRIX_RAIN,
    fontFamily: "'Courier New', monospace",
    fontWeight: 700,
    textColor: '#00FF41',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: false,
    entryAnimation: 'NONE',
    exitAnimation: 'NONE',
    wordHighlight: 'COLOR_POP',
    animationSpeed: 'FAST',
  },

  // ─── TYPOGRAPHY CAPTION PRESETS (Sprint 5) ───
  {
    id: 'typo-size-hierarchy',
    name: 'Size Hierarchy',
    category: 'Typography',
    description: 'Small context + GIANT accent word + small context (Image 1 style)',
    icon: '📐',
    captionStyle: CaptionStyle.TYPO_SIZE_HIERARCHY,
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: 900,
    textColor: '#FFFFFF',
    bgEnabled: false,
    bgColor: 'transparent',
    bgPadding: 0,
    bgRadius: 0,
    strokeWidth: 0,
    strokeColor: 'transparent',
    uppercase: true,
    entryAnimation: 'NONE',
    exitAnimation: 'NONE',
    wordHighlight: 'NONE',
    animationSpeed: 'MEDIUM',
  },
];

// ─────────────────────────────────────────────────────────
// EMOTION → STYLE MAPPING
// ─────────────────────────────────────────────────────────

export interface EmotionStyleMapping {
  entryAnimation: EntryAnimation;
  animationSpeed: 'FAST' | 'MEDIUM' | 'SLOW';
  wordHighlight: WordHighlightMode;
  textColorOverride?: string;
}

export const EMOTION_STYLE_MAP: Record<string, EmotionStyleMapping> = {
  energetic: {
    entryAnimation: 'BOUNCE',
    animationSpeed: 'FAST',
    wordHighlight: 'COLOR_POP',
    textColorOverride: '#FF6B6B',
  },
  calm: {
    entryAnimation: 'FADE_IN',
    animationSpeed: 'SLOW',
    wordHighlight: 'SPOTLIGHT',
  },
  serious: {
    entryAnimation: 'SLIDE_UP',
    animationSpeed: 'MEDIUM',
    wordHighlight: 'UNDERLINE',
  },
  joyful: {
    entryAnimation: 'ZOOM_IN',
    animationSpeed: 'FAST',
    wordHighlight: 'KARAOKE',
    textColorOverride: '#FACC15',
  },
};

// ─────────────────────────────────────────────────────────
// AI AUTO-STYLE SUGGESTION
// ─────────────────────────────────────────────────────────

export interface AIStyleSuggestion {
  theme: string;
  fontFamily: string;
  textColor: string;
  entryAnimation: string;
  wordHighlight: string;
  reasoning: string;
}

export const generateAIStyleSuggestion = async (
  captions: Caption[]
): Promise<AIStyleSuggestion> => {
  const apiKey = getApiKey();
  const ai = new GoogleGenAI({ apiKey });

  const transcript = captions.map(c => c.text).join(" ").substring(0, 5000);
  const sentiments = captions
    .filter(c => c.sentiment)
    .map(c => c.sentiment)
    .filter((v, i, arr) => arr.indexOf(v) === i);

  const availableThemes = THEME_PRESETS.map(t => t.id).join(', ');
  const systemInstruction = `
    You are an expert video caption stylist for viral short-form content.
    Analyze the transcript and suggest the optimal caption styling.
    
    Available themes: ${availableThemes}
    Available fonts: Inter, Montserrat, Bebas Neue, Bangers, Orbitron, Playfair Display, Fredoka, Anton, Poppins, Proxima Nova, Outfit, Space Mono, Caveat
    Available entry animations: NONE, SLIDE_UP, SLIDE_DOWN, FADE_IN, ZOOM_IN, BOUNCE, FLIP, FLIP_Y, ROTATE_IN, BLUR_IN, GLITCH, ELASTIC, SHATTER, STAMP, WIPE_RIGHT, SPLIT_OPEN, SPRING, SCATTER_IN, POP, SCALE_UP
    Available word highlights: NONE, KARAOKE, SPOTLIGHT, COLOR_POP, UNDERLINE, BOX, FIRE, RAINBOW, WAVE, SPARKLE
    
    Detected sentiments: ${sentiments.join(', ') || 'neutral'}
    
    Rules:
    - Match the energy and tone of the content
    - If motivational → bold, uppercase, heavy stroke
    - If casual/conversational → clean, modern, subtle
    - If funny/meme → loud, comic, colorful
    - If educational → professional, clean serif, minimal animation
    - If gaming/tech → neon, futuristic font
    
    Return ONLY valid JSON.
  `;

  try {
    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: [{ text: `TRANSCRIPT: ${transcript}` }]
      },
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            theme: { type: Type.STRING, description: "Best matching theme ID" },
            fontFamily: { type: Type.STRING, description: "Recommended font family" },
            textColor: { type: Type.STRING, description: "Hex color for text" },
            entryAnimation: { type: Type.STRING, description: "Recommended entry animation" },
            wordHighlight: { type: Type.STRING, description: "Recommended word highlight mode" },
            reasoning: { type: Type.STRING, description: "Brief explanation why this style fits" },
          },
          required: ["theme", "fontFamily", "textColor", "entryAnimation", "wordHighlight", "reasoning"]
        }
      }
    });

    const text = response.text || '{}';
    return JSON.parse(text) as AIStyleSuggestion;
  } catch (error) {
    console.error("AI Style Suggestion Error:", error);
    // Fallback to motivation theme
    return {
      theme: 'motivation',
      fontFamily: "'Bebas Neue', display",
      textColor: '#FACC15',
      entryAnimation: 'BOUNCE',
      wordHighlight: 'KARAOKE',
      reasoning: 'Default fallback — motivational style applied.'
    };
  }
};

// ─────────────────────────────────────────────────────────
// HOOK TEXT SUGGESTIONS
// ─────────────────────────────────────────────────────────

export const generateHookSuggestions = async (
  captions: Caption[]
): Promise<string[]> => {
  const apiKey = getApiKey();
  const ai = new GoogleGenAI({ apiKey });

  const transcript = captions.map(c => c.text).join(" ").substring(0, 5000);

  const systemInstruction = `
    You are a viral short-form content strategist.
    Generate 5 attention-grabbing hook texts for the first 3 seconds of a video.
    
    Rules:
    - Each hook must be 2-5 words
    - Create curiosity or shock value
    - Use action verbs and power words
    - Mix question hooks, statement hooks, and challenge hooks
    
    Return ONLY a JSON array of strings.
  `;

  try {
    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: [{ text: `VIDEO TRANSCRIPT: ${transcript}` }]
      },
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: { type: Type.STRING }
        }
      }
    });

    const text = response.text || '[]';
    return JSON.parse(text) as string[];
  } catch (error) {
    console.error("Hook Suggestion Error:", error);
    return ["Watch This 🔥", "You Won't Believe...", "STOP Scrolling ✋", "Here's The Truth", "This Changes Everything"];
  }
};
