/**
 * Motion Graphics Quality Scoring System
 *
 * Provides quality assessments for all 98 motion graphics templates, including:
 * - Scoring across 10 dimensions (1-10 scale)
 * - Recommendation status (KEEP, IMPROVE, HIDE, REMOVE)
 * - Issue tracking and improvement fixes
 * - Filtering functions for production-ready templates
 */

import { PrimitiveType } from '../motionGraphicsService';

export interface TemplateQualityScore {
  templateName: string;
  overallScore: number;          // 1-10
  visualPolish: number;          // 1-10
  usefulnessRating: number;      // 1-10
  animationQuality: number;      // 1-10
  textRendering: number;         // 1-10
  colorSystem: number;           // 1-10
  sizing: number;                // 1-10
  completeness: number;          // 1-10
  uniqueness: number;            // 1-10
  compatibility: number;         // 1-10
  recommendation: 'KEEP' | 'IMPROVE' | 'HIDE' | 'REMOVE';
  issues: string[];
  fixes: string[];
}

/**
 * QUALITY_SCORES constant mapping all 98 templates to quality assessments.
 * Templates are scored across 10 dimensions and categorized by recommendation.
 */
export const QUALITY_SCORES: Record<string, TemplateQualityScore> = {
  // TIER 1: PRODUCTION READY (9.0+)
  'big-text-reveal': {
    templateName: 'Big Text Reveal',
    overallScore: 9.5,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 10,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 8,
    compatibility: 10,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'camera-zoom-3d': {
    templateName: '3D Camera Zoom',
    overallScore: 9.5,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 10,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'particle-burst': {
    templateName: 'Particle Burst',
    overallScore: 9.5,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 10,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 10,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'glitch-text': {
    templateName: 'Glitch Text',
    overallScore: 9.2,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 8,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'light-sweep': {
    templateName: 'Light Sweep',
    overallScore: 9.2,
    visualPolish: 10,
    usefulnessRating: 8,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 10,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'aurora-text': {
    templateName: 'Aurora Text',
    overallScore: 9.3,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 10,
    colorSystem: 10,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'shimmer-text': {
    templateName: 'Shimmer Text',
    overallScore: 9.1,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 10,
    colorSystem: 9,
    sizing: 9,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'hyper-text': {
    templateName: 'Hyper Text',
    overallScore: 9.2,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 10,
    colorSystem: 8,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'liquid-morph': {
    templateName: 'Liquid Morph Transition',
    overallScore: 9.4,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 10,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'text-3d': {
    templateName: '3D Extruded Text',
    overallScore: 9.3,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 10,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'neural-intelligence-core': {
    templateName: 'Neural Intelligence Core',
    overallScore: 9.5,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 10,
    sizing: 10,
    completeness: 10,
    uniqueness: 10,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'bento-grid': {
    templateName: 'Bento Grid Reveal',
    overallScore: 9.4,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'card-carousel-3d': {
    templateName: '3D Card Flip Carousel',
    overallScore: 9.3,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'cursor-click-ui': {
    templateName: 'Cursor Click & UI Reveal',
    overallScore: 9.4,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 9,
    sizing: 10,
    completeness: 9,
    uniqueness: 10,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'versus-duel': {
    templateName: 'Versus Split Duel',
    overallScore: 9.3,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'device-tilt-3d': {
    templateName: '3D Device Tilt',
    overallScore: 9.4,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'search-rank-list': {
    templateName: 'Google Search Rank List',
    overallScore: 9.3,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'cinematic-title-opener': {
    templateName: 'Cinematic Title Opener',
    overallScore: 9.4,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 9,
    sizing: 10,
    completeness: 9,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },

  // TIER 2: HIGH QUALITY (8.0-8.9)
  'lower-third': {
    templateName: 'Lower Third',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'icon-burst': {
    templateName: 'Icon Burst',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'counter': {
    templateName: 'Counter',
    overallScore: 8.9,
    visualPolish: 9,
    usefulnessRating: 10,
    animationQuality: 9,
    textRendering: 10,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'highlight-box': {
    templateName: 'Highlight Box',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 8,
    textRendering: 8,
    colorSystem: 8,
    sizing: 9,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'bar-reveal': {
    templateName: 'Bar Reveal',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'bg-gradient-pulse': {
    templateName: 'Background Pulse',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'transition-wipe': {
    templateName: 'Transition Wipe',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'quote-card': {
    templateName: 'Quote Card',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'bullet-list-reveal': {
    templateName: 'Bullet List',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'callout-arrow': {
    templateName: 'Callout Arrow',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'word-emphasis-flash': {
    templateName: 'Word Flash',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'animated-arrow': {
    templateName: 'Animated Arrow',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'meteors': {
    templateName: 'Meteors',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'ripple': {
    templateName: 'Ripple',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'retro-grid': {
    templateName: 'Retro Grid',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 9,
    completeness: 8,
    uniqueness: 9,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'border-beam': {
    templateName: 'Border Beam',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'spotlight': {
    templateName: 'Spotlight',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'morph-text': {
    templateName: 'Morph Text',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'typewriter': {
    templateName: 'Typewriter',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 10,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'kinetic-text': {
    templateName: 'Kinetic Text',
    overallScore: 8.9,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'shockwave': {
    templateName: 'Shockwave',
    overallScore: 8.8,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 7,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'confetti': {
    templateName: 'Confetti',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'wave-text': {
    templateName: 'Wave Text',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'fire-text': {
    templateName: 'Fire Text',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'countdown': {
    templateName: 'Countdown',
    overallScore: 8.9,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'glitch-screen': {
    templateName: 'Glitch Screen',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'neon-sign': {
    templateName: 'Neon Sign',
    overallScore: 8.8,
    visualPolish: 10,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'liquid-bg': {
    templateName: 'Liquid BG',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'scene-3d': {
    templateName: '3D World Scene',
    overallScore: 8.9,
    visualPolish: 10,
    usefulnessRating: 8,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 9,
    sizing: 9,
    completeness: 8,
    uniqueness: 9,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'camera-cinematic': {
    templateName: 'Cinematic Camera',
    overallScore: 9.0,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 10,
    textRendering: 8,
    colorSystem: 9,
    sizing: 9,
    completeness: 9,
    uniqueness: 9,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'glass-panel': {
    templateName: 'Glassmorphism Panel',
    overallScore: 8.9,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'cyber-hud': {
    templateName: 'Cyber HUD',
    overallScore: 8.8,
    visualPolish: 10,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 9,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'marquee-text': {
    templateName: 'Marquee Text',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'notification-stack': {
    templateName: 'Notification Stack',
    overallScore: 8.8,
    visualPolish: 10,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 9,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'code-terminal-ui': {
    templateName: 'Code Terminal UI',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 10,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'animated-emoji-button': {
    templateName: 'Animated Emoji Button',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'glass-toggle': {
    templateName: 'Glass Toggle Switch',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'circular-progress': {
    templateName: 'Circular Progress Ring',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'pricing-table': {
    templateName: 'Pricing Table Cards',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 10,
    animationQuality: 8,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'testimonial-rotator': {
    templateName: 'Testimonial Rotator',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 10,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'ai-chat-message': {
    templateName: 'AI Chat Message',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'floating-product-card': {
    templateName: 'Floating Product Card',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 8,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'morphing-shapes': {
    templateName: 'Morphing Shapes',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 7,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 9,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'gradient-orbs': {
    templateName: 'Gradient Orbs',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 7,
    animationQuality: 9,
    textRendering: 6,
    colorSystem: 10,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'before-after-reveal': {
    templateName: 'Before / After Reveal',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 10,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'globe-3d': {
    templateName: 'Globe 3D',
    overallScore: 8.8,
    visualPolish: 10,
    usefulnessRating: 8,
    animationQuality: 10,
    textRendering: 7,
    colorSystem: 9,
    sizing: 9,
    completeness: 8,
    uniqueness: 9,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'device-mockup': {
    templateName: 'Device Mockup',
    overallScore: 8.8,
    visualPolish: 10,
    usefulnessRating: 10,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 9,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'holo-projection': {
    templateName: 'Holographic Projection',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 7,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'liquid-loader': {
    templateName: 'Liquid Loader',
    overallScore: 8.7,
    visualPolish: 9,
    usefulnessRating: 7,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'magnetic-button': {
    templateName: 'Magnetic Button',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'spotlight-card': {
    templateName: 'Spotlight Card',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'neon-command-menu': {
    templateName: 'Neon Command Menu',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'floating-dock': {
    templateName: 'Floating Dock',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 7,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'holographic-card': {
    templateName: 'Holographic Card',
    overallScore: 8.7,
    visualPolish: 10,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 9,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'metrics-dashboard': {
    templateName: 'Metrics Dashboard',
    overallScore: 8.8,
    visualPolish: 9,
    usefulnessRating: 10,
    animationQuality: 9,
    textRendering: 9,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 7,
    compatibility: 8,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'map-route-tracker': {
    templateName: 'Interactive Map Tracker',
    overallScore: 8.6,
    visualPolish: 9,
    usefulnessRating: 8,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'dynamic-callout': {
    templateName: 'Blueprint Spec Callout',
    overallScore: 8.5,
    visualPolish: 9,
    usefulnessRating: 9,
    animationQuality: 9,
    textRendering: 8,
    colorSystem: 8,
    sizing: 8,
    completeness: 8,
    uniqueness: 8,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },

  // TIER 3: GOOD QUALITY (7.0-7.9)
  'ai-search-bar': {
    templateName: 'AI Search Bar',
    overallScore: 7.8,
    visualPolish: 8,
    usefulnessRating: 8,
    animationQuality: 8,
    textRendering: 8,
    colorSystem: 8,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'mesh-gradient-bg': {
    templateName: 'Mesh Gradient BG',
    overallScore: 7.5,
    visualPolish: 8,
    usefulnessRating: 6,
    animationQuality: 8,
    textRendering: 6,
    colorSystem: 9,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'scroll-reveal-stack': {
    templateName: 'Scroll Reveal Stack',
    overallScore: 7.6,
    visualPolish: 8,
    usefulnessRating: 7,
    animationQuality: 8,
    textRendering: 7,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'dynamic-island': {
    templateName: 'Dynamic Island',
    overallScore: 7.4,
    visualPolish: 8,
    usefulnessRating: 6,
    animationQuality: 8,
    textRendering: 7,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'floating-notification': {
    templateName: 'Floating Notification',
    overallScore: 7.7,
    visualPolish: 8,
    usefulnessRating: 8,
    animationQuality: 8,
    textRendering: 7,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'ai-thinking-loader': {
    templateName: 'AI Thinking Loader',
    overallScore: 7.6,
    visualPolish: 8,
    usefulnessRating: 7,
    animationQuality: 8,
    textRendering: 6,
    colorSystem: 8,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'network-graph': {
    templateName: 'Network Graph',
    overallScore: 7.5,
    visualPolish: 8,
    usefulnessRating: 6,
    animationQuality: 8,
    textRendering: 6,
    colorSystem: 8,
    sizing: 7,
    completeness: 7,
    uniqueness: 8,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'stacked-notes': {
    templateName: 'Stacked Notes',
    overallScore: 7.3,
    visualPolish: 8,
    usefulnessRating: 6,
    animationQuality: 7,
    textRendering: 7,
    colorSystem: 8,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'voice-waveform': {
    templateName: 'Voice Waveform',
    overallScore: 7.4,
    visualPolish: 8,
    usefulnessRating: 7,
    animationQuality: 8,
    textRendering: 6,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'shimmer-button': {
    templateName: 'Shimmer Button',
    overallScore: 7.5,
    visualPolish: 8,
    usefulnessRating: 7,
    animationQuality: 8,
    textRendering: 7,
    colorSystem: 8,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'pixel-transition': {
    templateName: 'Pixel Transition',
    overallScore: 7.2,
    visualPolish: 8,
    usefulnessRating: 6,
    animationQuality: 8,
    textRendering: 6,
    colorSystem: 7,
    sizing: 7,
    completeness: 6,
    uniqueness: 7,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'quantum-card-explosion': {
    templateName: 'Quantum Card Explosion',
    overallScore: 7.4,
    visualPolish: 8,
    usefulnessRating: 6,
    animationQuality: 8,
    textRendering: 6,
    colorSystem: 8,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'split-text-reveal': {
    templateName: 'Split Text Reveal',
    overallScore: 7.6,
    visualPolish: 8,
    usefulnessRating: 7,
    animationQuality: 8,
    textRendering: 8,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 7,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'showcase-reel': {
    templateName: 'Showcase Reel',
    overallScore: 7.5,
    visualPolish: 8,
    usefulnessRating: 8,
    animationQuality: 8,
    textRendering: 7,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 6,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'title-opener': {
    templateName: 'Title Opener',
    overallScore: 7.4,
    visualPolish: 8,
    usefulnessRating: 8,
    animationQuality: 7,
    textRendering: 8,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 6,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },
  'trailer-title': {
    templateName: 'Trailer Title Slam',
    overallScore: 7.6,
    visualPolish: 8,
    usefulnessRating: 8,
    animationQuality: 8,
    textRendering: 8,
    colorSystem: 7,
    sizing: 7,
    completeness: 7,
    uniqueness: 7,
    compatibility: 6,
    recommendation: 'KEEP',
    issues: [],
    fixes: [],
  },

  // TIER 4: NEEDS IMPROVEMENT (5.0-6.9)
  'polaroid-stack': {
    templateName: 'Polaroid Stack',
    overallScore: 3.5,
    visualPolish: 5,
    usefulnessRating: 3,
    animationQuality: 4,
    textRendering: 4,
    colorSystem: 4,
    sizing: 3,
    completeness: 3,
    uniqueness: 4,
    compatibility: 2,
    recommendation: 'HIDE',
    issues: [
      'Niche/outdated aesthetic (vintage polaroid trend peaked)',
      'Poor text rendering on small cards',
      'Limited use cases in modern motion graphics',
      'Compatibility issues with tight layouts'
    ],
    fixes: [
      'Redesign as modern photo grid (testimonials/portfolio)',
      'Improve text sizing and readability',
      'Add responsive card layout options'
    ],
  },
  'infinite-logo-marquee': {
    templateName: 'Infinite Logo Marquee',
    overallScore: 3.0,
    visualPolish: 4,
    usefulnessRating: 3,
    animationQuality: 4,
    textRendering: 2,
    colorSystem: 3,
    sizing: 2,
    completeness: 2,
    uniqueness: 4,
    compatibility: 2,
    recommendation: 'HIDE',
    issues: [
      'Extremely niche use case (rarely needed)',
      'Poor text rendering and sizing flexibility',
      'Loops feel artificial and low-quality',
      'No real business value in most contexts'
    ],
    fixes: [
      'Remove or convert to generic scroll effect',
      'Create a horizontal carousel replacement',
      'Focus development on high-demand templates'
    ],
  },

  // TIER 5: MARKED FOR REMOVAL (< 5.0)
  'paper-tear': {
    templateName: 'Paper Tear',
    overallScore: 2.0,
    visualPolish: 3,
    usefulnessRating: 1,
    animationQuality: 2,
    textRendering: 2,
    colorSystem: 2,
    sizing: 2,
    completeness: 2,
    uniqueness: 3,
    compatibility: 1,
    recommendation: 'REMOVE',
    issues: [
      'Niche use case (VoxStyle stop-motion, outdated trend)',
      'Outdated aesthetic - 12fps jitter looks unprofessional in 2026',
      'Poor quality, difficult to read text integration',
      'Not suitable for professional motion graphics'
    ],
    fixes: [
      'Remove from main registry entirely',
      'Use liquid-morph or split-text-reveal as replacement'
    ],
  },
  'elastic-slider': {
    templateName: 'Elastic Slider',
    overallScore: 2.5,
    visualPolish: 2,
    usefulnessRating: 2,
    animationQuality: 3,
    textRendering: 2,
    colorSystem: 3,
    sizing: 2,
    completeness: 2,
    uniqueness: 3,
    compatibility: 2,
    recommendation: 'REMOVE',
    issues: [
      'Poor UX animation pattern (elastic feels sluggish)',
      'Text rendering issues with dynamic values',
      'Outdated interaction paradigm',
      'Major rewrite needed to be production-ready'
    ],
    fixes: [
      'Remove from registry',
      'Use card-carousel-3d for carousel needs instead'
    ],
  },
  'particle-trail-cursor': {
    templateName: 'Particle Trail Cursor',
    overallScore: 2.0,
    visualPolish: 2,
    usefulnessRating: 1,
    animationQuality: 3,
    textRendering: 1,
    colorSystem: 2,
    sizing: 1,
    completeness: 1,
    uniqueness: 4,
    compatibility: 2,
    recommendation: 'REMOVE',
    issues: [
      'Requires real-time cursor tracking (not viable in video)',
      'No text rendering capability',
      'Niche effect that rarely serves video narratives',
      'Poor performance in video export contexts'
    ],
    fixes: [
      'Remove entirely - fundamentally unsuited for video',
      'Use particle-burst or confetti for particle effects'
    ],
  },
  'flip-clock': {
    templateName: 'Flip Clock',
    overallScore: 2.5,
    visualPolish: 3,
    usefulnessRating: 2,
    animationQuality: 3,
    textRendering: 3,
    colorSystem: 2,
    sizing: 2,
    completeness: 2,
    uniqueness: 3,
    compatibility: 1,
    recommendation: 'REMOVE',
    issues: [
      'Retro novelty effect, rarely fits modern aesthetics',
      'Limited use case (only for clock/time displays)',
      'Awkward text integration',
      'Compatibility issues across devices'
    ],
    fixes: [
      'Remove from production registry',
      'Use countdown timer as replacement for time-based effects'
    ],
  },
  'text-scramble': {
    templateName: 'Text Scramble',
    overallScore: 5.5,
    visualPolish: 6,
    usefulnessRating: 5,
    animationQuality: 6,
    textRendering: 6,
    colorSystem: 5,
    sizing: 5,
    completeness: 5,
    uniqueness: 6,
    compatibility: 4,
    recommendation: 'IMPROVE',
    issues: [
      'Character-by-character scramble is hard to read',
      'Readability issues make it unsuitable for text-heavy beats',
      'Over-animated feel detracts from message clarity',
      'Needs significant animation refinement'
    ],
    fixes: [
      'Major rewrite: reduce scramble intensity',
      'Add character reveal speed control',
      'Improve text legibility during animation',
      'Consider morphing-text as alternative'
    ],
  },
};

/**
 * Get all templates filtered by minimum quality score
 */
export function getTemplatesByQuality(minScore: number): string[] {
  return Object.entries(QUALITY_SCORES)
    .filter(([, score]) => score.overallScore >= minScore)
    .map(([name]) => name);
}

/**
 * Get templates marked for removal (score < 4)
 */
export function getRemovalCandidates(): string[] {
  return Object.entries(QUALITY_SCORES)
    .filter(([, score]) => score.overallScore < 4)
    .map(([name]) => name);
}

/**
 * Get templates that need improvement (score 5-7)
 */
export function getImprovementCandidates(): string[] {
  return Object.entries(QUALITY_SCORES)
    .filter(([, score]) => score.overallScore >= 5 && score.overallScore < 8 && score.recommendation === 'IMPROVE')
    .map(([name]) => name);
}

/**
 * Get production-ready templates (score >= 8)
 */
export function getProductionReady(): string[] {
  return Object.entries(QUALITY_SCORES)
    .filter(([, score]) => score.overallScore >= 8)
    .map(([name]) => name);
}

/**
 * Get deprecated templates (marked HIDE)
 */
export function getDeprecated(): string[] {
  return Object.entries(QUALITY_SCORES)
    .filter(([, score]) => score.recommendation === 'HIDE')
    .map(([name]) => name);
}

/**
 * Validate a single template's quality and get production readiness
 */
export function validateTemplateQuality(templateName: string): {
  isProduction: boolean;
  score: number;
  issues: string[];
  suggestions: string[];
} {
  const score = QUALITY_SCORES[templateName];

  if (!score) {
    return {
      isProduction: false,
      score: 0,
      issues: ['Template not found in quality registry'],
      suggestions: ['Add template to quality scoring system'],
    };
  }

  return {
    isProduction: score.overallScore >= 8,
    score: score.overallScore,
    issues: score.issues,
    suggestions: score.fixes,
  };
}

/**
 * Get fallback templates for removed ones
 */
export const FALLBACK_TEMPLATES: Record<string, string> = {
  'paper-tear': 'liquid-morph',
  'elastic-slider': 'card-carousel-3d',
  'particle-trail-cursor': 'particle-burst',
  'flip-clock': 'countdown',
  'text-scramble': 'hyper-text',
};

/**
 * Substitute a template with a production-ready alternative if needed
 */
export function getSubstitute(templateName: string): string {
  const score = QUALITY_SCORES[templateName];

  // If template is marked for removal, use explicit fallback
  if (score && (score.recommendation === 'REMOVE' || score.overallScore < 4)) {
    return FALLBACK_TEMPLATES[templateName] || 'big-text-reveal';
  }

  // If template is hidden or needs improvement, suggest alternative
  if (score && score.recommendation === 'HIDE') {
    return 'morphing-shapes'; // generic alternative
  }

  return templateName;
}
